[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[[redirects]]
  from = "/api/etf-matrix"
  to = "/.netlify/functions/etf-matrix"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
